### ISSUE TITLE
Unable to download batch files for BIOMAG experiment part 1

### ISSUE THREAD

**Issue by anniegbryant** [Cogitate-consortium/cogitate-data#6]
Hello Cogitate Consortium team, my collaborators and I are excited to participate in the functional connectivity challenge in collaboration with BIOMAG2024! 

I have preregistered our team and created an account at https://www.arc-cogitate.com/ as instructed. I've confirmed that I'm logged in and have watched the tutorial video on how to download the bundle data, but when I try to download e.g. the "Batch 1 - MEG data + behav - file list" bundle, a new tab comes up that prompts me for a username and password (see attached screenshot). I entered the same username (my email) and password that I used to sign up for the Cogitate ARC website, but the popup just comes back up again prompting me to enter a username and password. Have I missed a step necessary to get access to the data?

<img width="1064" alt="Screenshot 2024-05-01 at 4 31 45 PM" src="https://github.com/Cogitate-consortium/cogitate-data/assets/28914677/814a3639-c216-4695-affa-02b4c94cfbe5">

Many thanks, Annie

**Comment by narvaria333** [comment]
Hello Cogitate Consortium team, We are also facing the same issue in downloading data bundles.

**Comment by pravsripad** [comment]
@anniegbryant @narvaria333 thank you for reporting the issue !

I can also reproduce the problem and will contact our team to fix it. Will keep you updated here.

**Comment by nbonacchi** [comment]
@anniegbryant @narvaria333 
Please try again

**Comment by anniegbryant** [comment]
Great, I'm able to download files from Batch 1 now. Thanks for your help!
