### ISSUE TITLE
Unable to download data bundles for batch 1 

### ISSUE THREAD

**Issue by narvaria333** [Cogitate-consortium/cogitate-data#7]
We have registered for the functional connectivity challenge under arc cogitate. We can access batch 1 MEG-BIDS data but are not able to access other batch 1 files which are displayed in the attached image file. It is asking for a username and password. However, it is denying access upon entering credentials which can be seen in the attached image. Also, We did not get username for the same. Please help.

Regards,
Abhishek Singh Narvaria
narvaria333@gmail.com

![Screenshot (1492)](https://github.com/Cogitate-consortium/cogitate-data/assets/68020011/0f2115d9-3e74-40ea-bbb8-e349ec9ba6ae)
![Screenshot (1493)](https://github.com/Cogitate-consortium/cogitate-data/assets/68020011/a37fbb20-7472-461e-9c2a-53a7b54acb55)

**Comment by nbonacchi** [comment]
@narvaria333 
can you please try again?

**Comment by narvaria333** [comment]
It's working now and we are able to download the data l. Thanks

**Comment by pravsripad** [comment]
@narvaria333 Thank you, please raise any other issues you may find here. 

@nbonacchi Thank you !
